### ISSUE TITLE
Please Fix My .sb3 Game

### ISSUE THREAD

**Issue by YeeDevelopment** [TurboWarp/sb3fix#10]
Hello, I've recently just used a software to recover my old data so I could find my old .sb3 projects. However, when I try to load one of them, they resault with this common error message: "Faild to unzip and extract project.json, with error: Error: Corrupted zip: can't find end of central directory".

It would be very much appreciated if anyone helps me get these projects back!!

Try recover: [https://drive.google.com/file/d/1aFNEpewkGhGm17gbOWK-q7KSsXiQhZvy/view?usp=sharing](url)
OR
Try convert this restore point file into .sb3 trbwp editor: [https://drive.google.com/file/d/1en6oPsa7VC9mGWXkaaYr5GYgXShkYV_F/view](url)

Email the fixed file to me: [yusuf.zahr134@gmail.com](url)
Appreciate for the help!

**Comment by GarboMuffin** [comment]
Check your email
