### ISSUE TITLE
SB3 file will not open Gets error about bad zip file

### ISSUE THREAD

**Issue by dogsarefunny** [TurboWarp/sb3fix#11]
This file was restored from win 11 shadow drive. Thanks in advance for your time and consideration.
[puppy worlds creature clone recovered.zip](https://github.com/TurboWarp/sb3fix/files/13883033/puppy.worlds.creature.clone.recovered.zip)

**Comment by GarboMuffin** [comment]
Hi, unfortunately most of that file is lost beyond repair. All I can get for you is a few scripts and a few costumes:

 - the project (only contains a few scripts from the stage) - https://static.muffin.ink/sb3fix-11-project.sb3
 - the assets - https://static.muffin.ink/sb3fix-11-assets.zip

While the part of the zip that says where to find each file was largely intact, the actual data for those files was mostly replaced by zeros.

Please make backups in the future, sorry :(

**Comment by dogsarefunny** [comment]
Thanks again for you help. Its kinda a happy accident I would not have found TurboWarp if it was not for this issue. I see why it happened when you open a fresh window in scratch desktop it does not display the file name at the top. Then someone well meaning clicked on save and saved over the original file. In turbo warp this is not the case. The other feature that we were missing from scratch desktop the backpack is also there. I have turned on windows file history and encouraged using a better backup strategy. Turbo warp should extend the life of our using blocky style coding and add hours of enjoyment. Thanks again
