### ISSUE TITLE
ScratchX project won't load in turbowarp

### ISSUE THREAD

**Issue by pooiod** [TurboWarp/sb3fix#12]
[box2Dcar.sbx](http://griffpatch.github.io/Box2D.js-Scratch2-Extension/examples/Box2d-Car-v0.3.sbx)
[sb3 variant](https://filedoge.com/download/e1d8feb2eaf77d1434e5db3bc2a6e523f5fc1ff78ae13dbf039e28a4475d918dd0cf990c9b3ca8874ae9)
When I load the project to change out the blocks, all of the extension blocks and most of the normal blocks are gone.
I tried manually going into the file, but I'm not familiar with the Scratch3 json and have no idea what to do

**Comment by GarboMuffin** [comment]
there's just a lot of problems here :(

 - ScratchX support was cooked up in one afternoon as a novelty; we can't make any promises about it working
 - the extension tries to load over HTTP, which is insecure so your browser blocks it (it should use HTTPS)
 - the project references blocks like "setBodyDamp" which simply don't exist in the extension
 - there are a lot of random errors that I can't find any reason to blame the ScratchX translation layer for
 - there is a modern equivalent Box2D extension

**Comment by pooiod** [comment]
I'm trying to swap the blocks for a modern equivalent
