### ISSUE TITLE
The project file's error.

### ISSUE THREAD

**Issue by Archiksb3** [TurboWarp/sb3fix#14]
Hello! I wanted to make a project in Turbowarp with name "Windows Physics". And i wanted to save, and i restart PC, and i wanted to open the project, but project not opened, and with error: Failed to unzip and extract project.json, with error: Error: Corrupted zip: can't find end of central directory. Please, help me!

**Comment by GarboMuffin** [comment]
File > Restore Points

**Comment by Archiksb3** [comment]
Im from Russia, and my language and region is Russia, can you type this second time, but on Russian language&

corrupted sb3 zip file: 
[Windows Physics.zip](https://github.com/TurboWarp/sb3fix/files/14514621/Windows.Physics.zip)

**Comment by Archiksb3** [comment]
@GarboMuffin (sorry for mention)

**Comment by GarboMuffin** [comment]
https://www.deepl.com/translator

The file you provided opens just fine for me

![image](https://github.com/TurboWarp/sb3fix/assets/33787854/f19aa0c3-f94b-458e-b672-eb68ec89a0cb)

**Comment by Archiksb3** [comment]
hmm.. strange..

**Comment by Archiksb3** [comment]
![image](https://github.com/TurboWarp/sb3fix/assets/162493455/446a849c-17ed-4940-b374-b3d17616c5b4)
but sb3 file dosen't want to open

**Comment by Archiksb3** [comment]
but can you fix how this error is? (i used translate site)

**Comment by Archiksb3** [comment]
![image](https://github.com/TurboWarp/sb3fix/assets/162493455/2796de6d-9bad-45bc-98c2-7e406a4faca6)
and i dont founded restore variants

**Comment by Archiksb3** [comment]
@GarboMuffin (sorry x2)

**Comment by Archiksb3** [comment]
@GarboMuffin (sorry x2

**Comment by Archiksb3** [comment]
@GarboMuffin (sorry x2)

**Comment by GarboMuffin** [comment]
I just renamed the zip you uploaded to .sb3 and it opened fine. If that's not working for you I rezipped it here: https://static.muffin.ink/sb3fix-14.sb3

By restore points I the button at the bottom of this menu:

![image](https://github.com/TurboWarp/sb3fix/assets/33787854/601097ce-9864-4d35-96ed-4e8e3a7818fc)

**Comment by Archiksb3** [comment]
Thank you so much!
