### ISSUE TITLE
please help!1!!1

### ISSUE THREAD

**Issue by Archiksb3** [TurboWarp/sb3fix#15]
@GarboMuffin hemp me please!!!
[Windows Physics.zip](https://github.com/TurboWarp/sb3fix/files/14514412/Windows.Physics.zip)
github dont want to anchor sb3 file, im from russia!! dont condemn me please!!1!11

**Comment by GarboMuffin** [comment]
keep the comments in https://github.com/TurboWarp/sb3fix/issues/14
