### ISSUE TITLE
My project is giving an "SyntaxError Unexpected token1' "

### ISSUE THREAD

**Issue by YuriKetsukane** [TurboWarp/sb3fix#16]
Hello, I threw my sb3. file to usb memory. When I transferred it back to my computer, it did not open the project. please help.

**Comment by YuriKetsukane** [comment]
> Hello, I threw my sb3. file to usb memory. When I transferred it back to my computer, it did not open the project. please help.

**Comment by GarboMuffin** [comment]
upload the file for us to examine it

most likely the USB drive died or you pulled it out of the computer without ejecting it; if that's the case i'm not sure how much we can do

**Comment by YuriKetsukane** [comment]
i will send tomorrow. i need sleep

7 Mar 2024 Per 22:19 tarihinde GarboMuffin ***@***.***> şunu
yazdı:

**Comment by GarboMuffin** [comment]
if you sent it, I didn't get it
