### ISSUE TITLE
“Project Failed to Load” & Sb3fix file wont show me fix 

### ISSUE THREAD

**Issue by SwazyKingX** [TurboWarp/sb3fix#19]
![BF61A6D2-D724-4224-A4BA-DDBBCCA23E28](https://github.com/TurboWarp/sb3fix/assets/38586048/3ea5c98d-464b-4ed3-922f-b944019a85f9)

**Comment by SwazyKingX** [comment]
If possible, i could email you the sb3 file at whatever email address and you can check it out but, I just hoped I could upload this file as an update to my game and I got this error and idk why.

**Comment by SwazyKingX** [comment]
@GarboMuffin 
Btw it says on the zip that my JSON is 2.3mb. Idk what the problem is

**Comment by GarboMuffin** [comment]
email it contact@turbowarp.org

**Comment by SwazyKingX** [comment]
I’ve sent it

**Comment by GarboMuffin** [comment]
set the link to be viewable by anyone with the link

**Comment by SwazyKingX** [comment]
@GarboMuffin

**Comment by SwazyKingX** [comment]
@GarboMuffin I’ve resent it and allowed access. It’s named “Yes.sb3”

**Comment by GarboMuffin** [comment]
So I've fixed the error you got, but the original Yes.sb3 file loads just fine for me, so sb3fix can't really help you at all.

What's wrong with the original project?

**Comment by SwazyKingX** [comment]
I guess it was the computer or something but, it never loaded and it was saying the project failed to load. I switched computers and i was able to update the game so its fine now. Thanks
