### ISSUE TITLE
Somehow managed to corrupt my project

### ISSUE THREAD

**Issue by St947** [TurboWarp/sb3fix#20]
Used a minimizer, Turbowarp and stuff, ended up causing corruption that corrupts the file (from making code disappear to a lot more,) whenever I try importing a SPRITE3 file into it, desperately want this to be fixed

Link to the file (pretty big, be warned)
https://www.mediafire.com/file/vcgi7wp5ej77ocz/ERSHFBuild%2528COMPRESSED%2529%25281%2529%25281%2529.sb3/file

**Comment by GarboMuffin** [comment]
im sorry this got lost in the noise

it was probably the minimizer you used

if you still need help getting it back, send another link, it wont get lost this time
