### ISSUE TITLE
Corrupted Scratch File I think

### ISSUE THREAD

**Issue by Neo-Zinogre** [TurboWarp/sb3fix#23]
My scratch files won't save! I have used your stuff and tried many, many thing. Please help!

**Comment by GarboMuffin** [comment]
you need to give us more details, we can't read your mind

what does "won't save" mean? do you get an error message? are you using the website or the desktop app? do the files save but not load? send a video perhaps?

**Comment by Neo-Zinogre** [comment]
https://github.com/user-attachments/assets/ab92f903-feae-48d3-a9a0-e323e0b4e112

This is just a short clip. Whenever I try to duplicate or make new sprites/add more code, it just says "Project couldn't save". I have no idea how to fix this. It has been going on for around 3 days, and I have tried everything I can think of. If you know anything I can do, I would very much appreciate it.

**Comment by GarboMuffin** [comment]
press command+option+i, switch to the console tab, and record the same video again, including both the console and the title bar from your browser/os

**Comment by GarboMuffin** [comment]
okay actually, are you trying to upload them to Scratch's servers? if so then there's not much we can do about that, but supposedly signing out and signing back in fixes it

**Comment by Neo-Zinogre** [comment]
Yeah pretty much, I am just trying to save it so it uploads. I know something about it is messed up and won't let me save it, so I just wanted to know if you guys could do anything about that. I have tried signing out then signing back in lol

**Comment by GarboMuffin** [comment]
well i guess you can do file > save to your computer and get that file to us somehow. but its possible we may not be able to help you if scratch's servers are misbehaving
