### ISSUE TITLE
Broken Image, I think.

### ISSUE THREAD

**Issue by L1ghtCrimson** [TurboWarp/sb3fix#24]
I was trying to build a friends list using a combination of the Gamejolt API and Asset Manager extensions. Everything was working just fine in the editor but when I try to load the saved project now, it gives me an error. 

{"validationError":"Could not parse as a valid SB2 or SB3 project.","sb3Errors":[{"keyword":"enum","dataPath":".targets[16].costumes[0].dataFormat","schemaPath":"#/properties/dataFormat/enum","params":{"allowedValues":["png","svg","jpeg","jpg","bmp","gif"]},"message":"should be equal to one of the allowed values"}],"sb2Errors":[{"keyword":"required","dataPath":"","schemaPath":"#/required","params":{"missingProperty":"objName"},"message":"should have required property 'objName'"}]}

I do not know how to go about solving this.

**Comment by L1ghtCrimson** [comment]
I think I might have figured it out slightly
I have it delete the old costumes so that it can upload the new one
it might see a sprite without any costume and get confused

**Comment by GarboMuffin** [comment]
Please send us the project file, either here or contact@turbowarp.org

**Comment by L1ghtCrimson** [comment]
[Neon Play.zip](https://github.com/user-attachments/files/16460589/Neon.Play.zip)

**Comment by GarboMuffin** [comment]
If you put the project into sb3fix now, the project you get out will load, though the broken costumes will be ? icons. May be able to fix that too at some point but getting it to load at all is more important
