### ISSUE TITLE
unsandboxed.org rotationStyle corruption 

### ISSUE THREAD

**Issue by thatoneham** [TurboWarp/sb3fix#27]
{"validationError":"Could not parse as a valid SB2 or SB3 project.","sb3Errors":[{"keyword":"enum","dataPath":".targets[1].rotationStyle","schemaPath":"sb3_definitions.json#/definitions/sprite/properties/rotationStyle/enum","params":{"allowedValues":["all around","don't rotate","left-right"]},"message":"should be equal to one of the allowed values"}],"sb2Errors":[{"keyword":"required","dataPath":"","schemaPath":"#/required","params":{"missingProperty":"objName"},"message":"should have required property 'objName'"}]}

---

URL: https://alpha.unsandboxed.org/?fps=60&size=640x360&offscreen&limitless#0
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0

**Comment by GarboMuffin** [comment]
@lilymakesthings you have to add your new rotation style to scratch-parser

**Comment by GarboMuffin** [comment]
@lilymakesthings scratch-parser dependency is here

https://github.com/Unsandboxed/scratch-vm/blob/73bef55e0142a02d885e6ad4144c9718de266572/package.json#L50

if you point that at your fork and update all the dependencies it probably works

**Comment by thatoneham** [comment]
so this is now fixed?

**Comment by LilyMakesThings** [comment]
no but I'll look into it now

**Comment by thatoneham** [comment]
sick
