### ISSUE TITLE
dumb project that failed to save at some point and now i am suffering the consequences

### ISSUE THREAD

**Issue by thefoxolotl** [TurboWarp/sb3fix#28]
i sent this in discord a bit ago but i thought Hmm maybe it would be a good idea to make a github issue too! so here we are
apparently at one point a few weeks ago a project i was working on decided to not save at some point and i never knew about it, so for some reason it regressed to a previous version which is weird considering the fact that the most recent version had already saved to my computer once before.. tried all the basic recovery methods, nothing worked so this is probably like my last resort.. i have the sb3 and the tw1029 if thats useful cuz Apparently that thing never got deleted so
i guess if this doesnt work then i can [very angrily] recreate everything that went missing but honestly im just pissed it happened in the first place
anyway sorry for rambling, if you can fix this for me i will be Very grateful!!
project sb3 - https://drive.google.com/file/d/16jDP76bmtlmRf_p7gggaAcPnCsBeEQLL/view?usp=sharing
tw1029 - https://drive.google.com/file/d/1Wtq2aSy0tJXxjMZYYv-Gy2dnnDqz9XjZ/view?usp=sharing

**Comment by GarboMuffin** [comment]
this looks mostly recoverable

**Comment by GarboMuffin** [comment]
It looks what happened is that you closed the desktop app before it finished saving. That's what the leftover .tw#### file means.

Your project's contents is interesting as 160MB of it is from two very large sounds that are 80MB each. You probably want to remove those or replace them with smaller versions. Even though the partial data is much smaller than the old version of the project most of the important parts can still be recovered because of that

https://static.muffin.ink/sb3fix-28.sb3

**Comment by thefoxolotl** [comment]
from the looks of it what i noticed was gone isnt there.. im not gonna make you go back and try again but it does sound like that could have probably been the reason
strangely enough the things that went missing had nothing to do with the songs, and the most recent version with those things had been saved days earlier so im not sure why it went back to a previous version of the file anyhow.. i guess i get why it probably didnt save but the part of how it went back to a much earlier version instead of the last version it was saved to is still confusing me

thanking you for your efforts anyway, once again you dont need to go back and retry [especially since from what im inferring, if it didnt get what i was looking for back the first time it probably wouldnt still have it unless its buried somewhere that i can't access] but its kinda nice information to have for the future
