### ISSUE TITLE
Scratch project broken.

### ISSUE THREAD

**Issue by CassieTheMoth** [TurboWarp/sb3fix#31]
Was making a Scratch Fusion 2 project but it's now broken/corrupt. I tried to fix it with the project fixer but it did not go through. https://drive.google.com/file/d/1grgnAY87ab67rudw38Xq7R4LXcJX2tKU/view?usp=sharing
[Moth Knight (Rearranged) compress.zip](https://github.com/user-attachments/files/17556871/Moth.Knight.Rearranged.compress.zip)

**Comment by GarboMuffin** [comment]
hi, sorry about the delay, here's what we can recover for you: https://static.muffin.ink/sb3fix-31.sb3
