### ISSUE TITLE
Corrupted project

### ISSUE THREAD

**Issue by Randomuser101101** [TurboWarp/sb3fix#32]
One day, my sb3 file got corrupted. First, it showed an error like this:
![스크린샷 2024-11-06 014007](https://github.com/user-attachments/assets/27b055b4-f70c-454d-a691-9896c3b54452)
https://drive.google.com/file/d/1xnjBnipZUqxd2fkok-Zn2cPNRyVP9z9w/view?usp=sharing

sb3fix couldn't repair the original project, so I tried to repair it using winRAR and then put it into sb3fix, then it showed me this error
![스크린샷 2024-11-06 013946](https://github.com/user-attachments/assets/a876cbb2-6a03-4a23-a5f3-13aedbcf2905)
https://drive.google.com/file/d/1ENERNuUbwr5MgYbnU7hFDxpmm1vZxs7i/view?usp=sharing

+I had a restore point, but it couldn't open because of this issue:
![스크린샷 2024-11-06 014019](https://github.com/user-attachments/assets/42e3e97b-5782-4746-853b-08da87a4ee7b)

**Comment by GarboMuffin** [comment]
seems that this is almost completely recoverable

**Comment by GarboMuffin** [comment]
https://static.muffin.ink/sb3fix-32.sb3

**Comment by Randomuser101101** [comment]
It works, thank you so much for the help!
