### ISSUE TITLE
MY BIG 2 MONTH PROJECT WONT FETCH(load)

### ISSUE THREAD

**Issue by fur1naa** [TurboWarp/sb3fix#34]
https://drive.google.com/file/d/11f9Xmb9R--yvCyOmWNTYZiXa8xJCB831/view?usp=sharing

yhea i know its a pmp but if u change it to sb3 it works the same

it doesnt load PLEASE fix this

**Comment by fur1naa** [comment]
> Your project is not corrupted, it is just too big for your computer to handle, so sb3fix wouldn't be able to help you.
> 
> Your largest problem is the hundreds of megabytes of big sound files that all get loaded before the project can start and end up being gigabytes of decoded audio data in RAM. The solution is to get rid of some of the big sounds. I can help you do that, if you would like.

yhea sure :D
but i had a even bigger project and that project worked fine
eh just do that anway

**Comment by GarboMuffin** [comment]
Have taken a second look now that I am home.

It refuses to load because the extension https://mubilop.tech/gallery/extensions/discordbot.js does not have CORS which apparently penguinmod requires.  That is something that penguinmod and mubilop.tech need to work out.

**Comment by GarboMuffin** [comment]
Here is a version of your project that will load

https://send.vis.ee/download/8252ca225eda7c7e/#YEWLS6d_XWKyOa-WeGMQmA

The link expires very soon so download it quick. If you need it again I'll keep the file around for a bit

I will reiterate that the root cause is that either mublilop.tech or penguinmod changed something and now your project was broken. So you should direct any bug reports to them. This is not a turbowarp bug or a scratch bug.

My comments about your project being too big are not strictly wrong. It takes about 10GB of RAM which after overheads was just barely able to fit into RAM on the computer I'm typing this on. Most of it is audio; if you can remove some of the big sounds that will help a lot.

**Comment by GarboMuffin** [comment]
@cicerorph @jeremygamer13 Summary: one of your respective projects changed something and almost ruined months of work by an end user. Try not to do that. Thanks.

**Comment by GarboMuffin** [comment]
I hope that the involved parties are mature enough to not prioritize petty drama with ruining the work of real people.

**Comment by cicerorph** [comment]
> I hope that the involved parties are mature enough to not prioritize petty drama over not ruining the work of real people.
> 
> If they aren't, maybe you should look for alternative software.

Hi, may I know what could be the issue with my extension?

**Comment by cicerorph** [comment]
> Have taken a second look now that I am home.
> 
> It refuses to load because the extension https://mubilop.tech/gallery/extensions/discordbot.js does not have CORS which apparently penguinmod requires.  That is something that penguinmod and mubilop.tech need to work out.

The website does actually have cors enabled on its source code, if you could probably give me more information that would be appreciated 🙏

**Comment by cicerorph** [comment]
> > @cicerorph @JeremyGamer13 Summary: one of your respective projects changed something and almost ruined months of work by an end user. Try not to do that. Thanks.
> 
> uhh dont ping mubi it isnt gonne help anything hes banned from pm forever for sending "questinable" femboy chat bubbles 😭 
> hes in kinda good terms with me but hates anybody else fr

Furina, as the creator of the extension, I remain responsible for my creations, regardless of whether I am banned from PenguinMod.

**Comment by cicerorph** [comment]
The CORS issue has been resolved, as a problem in the server code of my website had messed up the entire CORS system.

**Comment by GarboMuffin** [comment]
Fantastic, thanks

Try not to do that again :)

**Comment by JeremyGamer13** [comment]
> @cicerorph @JeremyGamer13 Summary: one of your respective projects changed something and ruined months of work by an end user. Try not to do that. Thanks.

we do not list the discordbot extension mentioned, this seems to just be a problem with the extension 🤷‍♂️
we are working on making some fallback local copy of extensions so this hopefully wont happen again once thats done

**Comment by cicerorph** [comment]
> > @cicerorph @JeremyGamer13 Summary: one of your respective projects changed something and ruined months of work by an end user. Try not to do that. Thanks.
> 
> we do not list the discordbot extension mentioned, this seems to just be a problem with the extension 🤷‍♂️
> we are working on making some fallback local copy of extensions so this hopefully wont happen again once thats done

(Off-topic)
By the way, Jeremy, if possible, could we discuss the Discord Auth API situation? I’ve managed to get the server back up, but I’m currently unable to integrate it into the extension again. Most of the time, all pull requests on the PenguinMod Extension Gallery go ignored, and I often had to request attention through the PenguinMod Discord Server.
