### ISSUE TITLE
{"missingProperty":"objName"},"message":"should have required property 'objName'"}]}

### ISSUE THREAD

**Issue by thatoneham** [TurboWarp/sb3fix#37]
{"validationError":"Could not parse as a valid SB2 or SB3 project.","sb3Errors":[{"keyword":"enum","dataPath":".targets[0].lists['Dwq{]Z@ysR:PFf@S(jd9'][2]","schemaPath":"#/additionalItems/enum","params":{"allowedValues":[true]},"message":"should be equal to one of the allowed values"}],"sb2Errors":[{"keyword":"required","dataPath":"","schemaPath":"#/required","params":{"missingProperty":"objName"},"message":"should have required property 'objName'"}]}

---

URL: https://alpha.unsandboxed.org/#0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0

file:
https://send.vis.ee/download/b49cca2f9782ebdb/#igKaJChe9oczYzqs6OwEUA

**Comment by thatoneham** [comment]
nevermind i fixed it by removing
, false in
"Dwq{]Z@ysR:PFf@S(jd9": ["Inventory", ["", "", "", ""], false]
and 
"g=I7H{;Mn8@jLK!-}_i[": ["Ammo", ["{\"light\":0}", "{\"heavy\":0}", "{\"shells\":0}"], false]

**Comment by GarboMuffin** [comment]
one has to wonder how that got there is the first place, then

**Comment by yuri-kiss** [comment]
> one has to wonder how that got there is the first place, then

this was an issue we (me and lily at unsandboxed) created on accident
