### ISSUE TITLE
Error: Could not load project

### ISSUE THREAD

**Issue by A7daanCC** [TurboWarp/sb3fix#38]
{"validationError":"Could not parse as a valid SB2 or SB3 project.","sb3Errors":[{"keyword":"enum","dataPath":".targets[14].rotationStyle","schemaPath":"sb3_definitions.json#/definitions/sprite/properties/rotationStyle/enum","params":{"allowedValues":["all around","don't rotate","left-right"]},"message":"should be equal to one of the allowed values"}],"sb2Errors":[{"keyword":"required","dataPath":"","schemaPath":"#/required","params":{"missingProperty":"objName"},"message":"should have required property 'objName'"}]}

---

URL: https://turbowarp.org/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0

**Comment by GarboMuffin** [comment]
looks fixable

**Comment by GarboMuffin** [comment]
If you put it into sb3fix again, you should get out a project that loads

If something else is still wrong, post it again here

**Comment by GarboMuffin** [comment]
"put it into sb3fix again" meaning put the file into https://turbowarp.github.io/sb3fix/
