### ISSUE TITLE
Yeah i have a truck load of files

### ISSUE THREAD

**Issue by machonessiebaby** [TurboWarp/sb3fix#4]
Okay so these are recovered files from an unintentional format of the wrong usb i recently got them back and found the sb3 repair site because almost every project leads to this error 
![image](https://github.com/TurboWarp/sb3fix/assets/56323671/78180383-1681-4b4f-b111-26f5dd9ae648)
and i opened some of them with notepad and they all look like this
![image](https://github.com/TurboWarp/sb3fix/assets/56323671/045e7df4-ab2f-49f5-9392-2ad90d087fe3)
so i used Sb3 fix but most of them dont work  (first letters missing on all of them weirdly)

https://drive.google.com/drive/folders/1jFU2icN50n2smXJhrI7sou7WTkPr1naM?usp=drive_link

**Comment by GarboMuffin** [comment]
https://static.muffin.ink/sb3fix-4.zip

Unfortunately only "_iggle - Copy.sb3" was recoverable enough to load, but even then most of the assets are missing

In the other files, a few music files were recoverable

Sorry, that's about all I can do. A formatted drive is one of the worst scenarios to deal with

**Comment by machonessiebaby** [comment]
well thank you for trying on most i think i can recover assets as i do have the sprite sheets
