### ISSUE TITLE
So, I was editing a project last night.

### ISSUE THREAD

**Issue by LGM-Productions** [TurboWarp/sb3fix#5]
So, I was editing a project in Turbowarp last night and saved it during that time. Now, when I woke up, my sb3 file is now corrupted. If you are able to recover some of the assets from the game, that would be great.

Here is the project link. (Had to host it there because the file is too large for GitHub.): https://mega.nz/file/VPVWQQjI

Key/Password (if needed): 8Db7La3Yn01iBqnB3XTQbXmNLveD7pbX5qNHnfO9ZyU

**Comment by GarboMuffin** [comment]
hey, this is all I could get. the scripts and a few audio files, sorry https://static.muffin.ink/sb3fix-5.sb3

--

are you using the website or desktop app (and which version?)?

**Comment by GarboMuffin** [comment]
do try File > Load restore point if you haven't already, you might be in luck

**Comment by LGM-Productions** [comment]
> hey, this is all I could get. the scripts and a few audio files, sorry https://static.muffin.ink/sb3fix-5.sb3
> 
> --
> 
> are you using the website or desktop app (and which version?)?

I was using the website version. I also recovered some assets from previous versions of my game.

**Comment by GarboMuffin** [comment]
nothing else I can do :(
