### ISSUE TITLE
fix 2 different variables having the same id

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [TurboWarp/sb3fix#6]
there's a bug in https://scratch.mit.edu/projects/794184180/ with this issue

**Comment by Bluecube5997thefan** [comment]
Cool

**Comment by GarboMuffin** [comment]
Without elaboration on what the bug is I'll have to close this, not playing an entire game just to maybe see a bug that could also just be a logic error in the game

(the project does load successfully, so fixing this in sb3fix is very low priority)
