### ISSUE TITLE
i am turbowarp porject broken

### ISSUE THREAD

**Issue by turbowarp114514** [TurboWarp/sb3fix#7]
[dms.txt](https://github.com/TurboWarp/sb3fix/files/12406556/dms.txt)

**Comment by GarboMuffin** [comment]
here's what I was able to recover:

https://static.muffin.ink/sb3fix-7.sb3

seems that most of it was recoverable, just some missing sounds.

please make backups in the future, and try File > Restore Points

**Comment by GarboMuffin** [comment]
Also, we're trying to figure out why these happen, what browser are you using / or are you using the desktop app?
