### ISSUE TITLE
Please help me open the project

### ISSUE THREAD

**Issue by NguyennbVietNam** [TurboWarp/sb3fix#8]
[Duaxe.zip](https://github.com/TurboWarp/sb3fix/files/12420133/Duaxe.zip)

**Comment by GarboMuffin** [comment]
This is fixable, give me a few minutes

**Comment by GarboMuffin** [comment]
Just pushed some new fixes to sb3fix that will make your project work. Do let me know if it still doesn't work

https://turbowarp.github.io/sb3fix/

**Comment by NguyennbVietNam** [comment]
It still doesn't work

**Comment by GarboMuffin** [comment]
Here is the fixed file

https://static.muffin.ink/sb3fix-8.sb3

Do you get an error loading that? Please tell me what error

**Comment by NguyennbVietNam** [comment]
Thanks you
